FGI = {
	L = {},
}
FGI_MAXLVL = 120
FGI_MINLVL = 1
FGI_DEFAULT_SEARCHINTERVAL = 5
FGI_DEFAULT_RACEFILTERSTART = FGI_MAXLVL +1
FGI_DEFAULT_CLASSFILTERSTART = FGI_MAXLVL +1
FGI_SCANINTERVALTIME = 7
FGI_FILTERSLIMIT = 21
FGI_MAXWHORETURN = 50
FGI_MAXWHOQUERY = 200
FGI_RESETSENDDBTIME = 604800	-- 1 week